# print("Hello world.!!!")
# print("welcome to my code")
# a=10
# b=20
# print("a+b")
# open
# nums = [1,2,3,4,5]
# print(min(nums))
# print(max(nums))
# print(min(nums))
# nums = (1,2,3,4,5)
# print(min(nums))
# from time import sleep


# print(10)
# print(10)
# x = 10
# print(x)
# a = 1
# b = 2
# print (a)
# print (b)
# print ('a+b')
# print(a+b)
# y = ('i am a boy who do not care about people')
# print (y) 


# print (10)
# print(0o10)
# print(0o12)
# print(0b10)
# print(0B10)
# print(0x10)
# print(0x11)
# type(4.2)
# print(1.79e308)
# print(5e-324)
# # print('footbar')
# name = input("plese enter your name :")
# age = input("please enter your age :")
# hobby1 = input("please enter your hobby :")
# hobby2 = input("please enter another hobby: ")
# print("\n", name.title(), "is", age,r"year old. \nHubbies are listed below.")
# print("\t-", hobby1)
# print("\t-", hobby2)
# TRIPPLE QUOTED STRINGS
# Drama = """Ali is a good boy, he sings afro beat and likes to edxperiment.
# One day, Ali went to the board of directors,
# This is what he said,
# "I think am ready to take over the company".
#                       Regards
#                       Alaba,
#                       Story for the gods."""
# print(Drama)
# # BOOLEANS DATE TYPE AND BOOL CONVERSION BULTIN FUNCTION
# print(bool(1))
# print(bool(2))
# print(bool(3))
print(divmod(20,3))
print(str)






